names_hash={'aaron-amanor-atter': 'aaron-amanor-atter',
    'abdel-fatao-hamidu': 'abdel-fatao-hamidu',
    'albert-kofi-kwansah-ansah': 'albert-kofi-kwansah-ansah',
    'amankwah-andy-prempeh': 'amankwah-andy-prempeh',
    'anku-jude-delali': 'anku-jude-delali',
    'ann-ampofoa-dwamena': 'ann-ampofoa-dwamena',
    'annor-mante-precious': 'annor-mante-precious',
    'anthony-mensah': 'anthony-mensah',
    'bernard-kirk-adjarnor-katamanso': 'bernard-kirk-adjarnor-katamanso',
    'bright-sefah': 'bright-sefah',
    'charles-buckle-cornah': 'charles-buckle-cornah',
    'clifford-kingsley-baidoo': 'clifford-kingsley-baidoo',
    'david-kwabena-arhin': 'david-kwabena-arhin',
    'dr.-ebenezer-anohah': 'dr.-ebenezer-anohah',
    'edward-attram-menya': 'edward-attram-menya',
    'edwin-adu-boateng': 'edwin-adu-boateng',
    'emily-wepiah-wobi': 'emily-wepiah-wobi',
    'emmanuel-gyan-ansah': 'emmanuel-gyan-ansah',
    'emmanuel-kissi-addo': 'emmanuel-kissi-addo',
    'emmanuel-selase-tormeti': 'emmanuel-selase-tormeti',
    'enyonam-beatson-affram': 'enyonam-beatson-affram',
    'eric-affum': 'eric-affum',
    'esegbe-able-katapu': 'esegbe-able-katapu',
    'eugget-nyarko-wireko': 'eugget-nyarko-wireko',
    'evans-obu': 'evans-obu',
    'felix-aryeh': 'felix-aryeh',
    'francisca-chidimma-chika': 'francisca-chidimma-chika',
    'frederick-edem-junior-broni': 'frederick-edem-junior-broni',
    'gaius-junior-erzoah': 'gaius-junior-erzoah',
    'hanisha-abdul-majid': 'hanisha-abdul-majid',
    'irene-ofoley-okine': 'irene-ofoley-okine',
    'isaac-junior-nyemekye': 'isaac-junior-nyemekye',
    'ivy-botchway': 'ivy-botchway',
    'jeffery-offei-darko': 'jeffery-offei-darko',
    'jennifer-acheampong': 'jennifer-acheampong',
    'jonas-kwamina-mensah-botwe-ankorah': 'jonas-kwamina-mensah-botwe-ankorah',
    'karen-akua-hanson': 'karen-akua-hanson',
    'kingsley-anim': 'kingsley-anim',
    'mensah-sitti': 'mensah-sitti',
    'moses-tetteh': 'moses-tetteh',
    'noah-otinkorang-boye': 'noah-otinkorang-boye',
    'nyarko-osei-yaw-joseph': 'nyarko-osei-yaw-joseph',
    'paul-kofi-bekai-botchwey': 'paul-kofi-bekai-botchwey',
    'raymond-swanzy': 'raymond-swanzy',
    'richelle-abakah-asmah': 'richelle-abakah-asmah',
    'sibdou-ibrahim-issifu': 'sibdou-ibrahim-issifu',
    'stephen-anokye': 'stephen-anokye',
    'taufik-kondor': 'taufik-kondor',
    'victor-okyere': 'victor-okyere',
    'vincent-mwintieru-nofong': 'vincent-mwintieru-nofong',
    'vine-volsugka-kelwini': 'vine-volsugka-kelwini',
    'emmanuel-kwesi-tandoh': 'emmanuel-kwesi-tandoh',
    'eunice-adwoa-kessewaa': 'eunice-adwoa-kessewaa',
    'henrietta-nutifafa-kessie': 'henrietta-nutifafa-kessie',
    'karikari-alex': 'karikari-alex',
    'kwamena-essiful-ansah': 'kwamena-essiful-ansah',
    'kwarteng-moses-adu': 'kwarteng-moses-adu',
    'samuel-boakye-agyarko': 'samuel-boakye-agyarko',
    'sylvia-famieh-quines': 'sylvia-famieh-quines'
}

repeated_names_list=[
    'aaron-amanor-atter-aaron-amanor-atter',
    'abdel-fatao-hamidu-abdel-fatao-hamidu',
    'albert-kofi-kwansah-ansah-albert-kofi-kwansah-ansah',
    'amankwah-andy-prempeh-amankwah-andy-prempeh',
    'anku-jude-delali-anku-jude-delali',
    'ann-ampofoa-dwamena-ann-ampofoa-dwamena',
    'annor-mante-precious-annor-mante-precious',
    'anthony-mensah-anthony-mensah',
    'bernard-kirk-adjarnor-katamanso-bernard-kirk-adjarnor-katamanso',
    'bright-sefah-bright-sefah',
    'charles-buckle-cornah-charles-buckle-cornah',
    'clifford-kingsley-baidoo-clifford-kingsley-baidoo',
    'david-kwabena-arhin-david-kwabena-arhin',
    'dr.-ebenezer-anohah-dr.-ebenezer-anohah',
    'edward-attram-menya-edward-attram-menya',
    'edwin-adu-boateng-edwin-adu-boateng',
    'emily-wepiah-wobi-emily-wepiah-wobi',
    'emmanuel-gyan-ansah-emmanuel-gyan-ansah',
    'emmanuel-kissi-addo-emmanuel-kissi-addo',
    'emmanuel-selase-tormeti-emmanuel-selase-tormeti',
    'enyonam-beatson-affram-enyonam-beatson-affram',
    'eric-affum-eric-affum',
    'esegbe-able-katapu-esegbe-able-katapu',
    'eugget-nyarko-wireko-eugget-nyarko-wireko',
    'evans-obu-evans-obu',
    'felix-aryeh-felix-aryeh',
    'francisca-chidimma-chika-francisca-chidimma-chika',
    'frederick-edem-junior-broni-frederick-edem-junior-broni',
    'gaius-junior-erzoah-gaius-junior-erzoah',
    'hanisha-abdul-majid-hanisha-abdul-majid',
    'irene-ofoley-okine-irene-ofoley-okine',
    'isaac-junior-nyemekye-isaac-junior-nyemekye',
    'ivy-botchway-ivy-botchway',
    'jeffery-offei-darko-jeffery-offei-darko',
    'jennifer-acheampong-jennifer-acheampong',
    'jonas-kwamina-mensah-botwe-ankorah-jonas-kwamina-mensah-botwe-ankorah',
    'karen-akua-hanson-karen-akua-hanson',
    'kingsley-anim-kingsley-anim',
    'mensah-sitti-mensah-sitti',
    'moses-tetteh-moses-tetteh',
    'noah-otinkorang-boye-noah-otinkorang-boye',
    'nyarko-osei-yaw-joseph-nyarko-osei-yaw-joseph',
    'paul-kofi-bekai-botchwey-paul-kofi-bekai-botchwey',
    'raymond-swanzy-raymond-swanzy',
    'richelle-abakah-asmah-richelle-abakah-asmah',
    'sibdou-ibrahim-issifu-sibdou-ibrahim-issifu',
    'stephen-anokye-stephen-anokye',
    'taufik-kondor-taufik-kondor',
    'victor-okyere-victor-okyere',
    'vincent-mwintieru-nofong-vincent-mwintieru-nofong',
    'vine-volsugka-kelwini-vine-volsugka-kelwini'
]

names_list=[
    'aaron-amanor-atter',
    'abdel-fatao-hamidu',
    'albert-kofi-kwansah-ansah',
    'amankwah-andy-prempeh',
    'anku-jude-delali',
    'ann-ampofoa-dwamena',
    'annor-mante-precious',
    'anthony-mensah',
    'bernard-kirk-adjarnor-katamanso',
    'bright-sefah',
    'charles-buckle-cornah',
    'clifford-kingsley-baidoo',
    'david-kwabena-arhin',
    'dr.-ebenezer-anohah',
    'edward-attram-menya',
    'edwin-adu-boateng',
    'emily-wepiah-wobi',
    'emmanuel-gyan-ansah',
    'emmanuel-kissi-addo',
    'emmanuel-selase-tormeti',
    'enyonam-beatson-affram',
    'eric-affum',
    'esegbe-able-katapu',
    'eugget-nyarko-wireko',
    'evans-obu',
    'felix-aryeh',
    'francisca-chidimma-chika',
    'frederick-edem-junior-broni',
    'gaius-junior-erzoah',
    'hanisha-abdul-majid',
    'irene-ofoley-okine',
    'isaac-junior-nyemekye',
    'ivy-botchway',
    'jeffery-offei-darko',
    'jennifer-acheampong',
    'jonas-kwamina-mensah-botwe-ankorah',
    'karen-akua-hanson',
    'kingsley-anim',
    'mensah-sitti',
    'moses-tetteh',
    'noah-otinkorang-boye',
    'nyarko-osei-yaw-joseph',
    'paul-kofi-bekai-botchwey',
    'raymond-swanzy',
    'richelle-abakah-asmah',
    'sibdou-ibrahim-issifu',
    'stephen-anokye',
    'taufik-kondor',
    'victor-okyere',
    'vincent-mwintieru-nofong',
    'vine-volsugka-kelwini',
      'emmanuel-kwesi-tandoh' ,
    'eunice-adwoa-kessewaa' ,
    'henrietta-nutifafa-kessie' ,
    'karikari-alex' ,
    'kwamena-essiful-ansah' ,
    'kwarteng-moses-adu' ,
    'samuel-boakye-agyarko' ,
    'sylvia-famieh-quines' 
]
